// CONSTANTS FOR CONFIGURATION

// HISTORY_H
const char _HISTORY_FILENAME[] = ".meushell.hst";
const int _HISTORY_INITIAL_CAPACITY = 100;

// ENV_H
const int _ENV_INITIAL_CAPACITY = 100;

// UTILS_H
const int _COMMAND_SIZE = 2048;

